version: '3.8'

services:
  inventory_export:
    build: ./inventory_export_app
    ports:
      - "5005:5005"
    environment:
      - API_CODE=${API_CODE}
      - APP_NAME=${APP_NAME}
      - DB_ALIAS=${DB_ALIAS}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    volumes:
      - ./data:/app/data

  meal_planner:
    build: ./meal_planner
    ports:
      - "8000:8000"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory_export:5005
    volumes:
      - ./data:/app/data
    depends_on:
      - inventory_export